/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UnoApp: typeof import('./components/_core/UnoApp.vue')['default']
    UnoAppBar: typeof import('./components/_core/UnoAppBar.vue')['default']
    UnoButton: typeof import('./components/_core/UnoButton.vue')['default']
    UnoContent: typeof import('./components/_core/UnoContent.vue')['default']
    UnoPage: typeof import('./components/_core/UnoPage.vue')['default']
  }
}
